# Generated by Django 4.2.5 on 2023-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelimage",
            name="image",
        ),
        migrations.AlterField(
            model_name="hotel",
            name="banner_image",
            field=models.ImageField(upload_to="hotels/"),
        ),
    ]
