# Generated by Django 4.2.5 on 2023-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_hotelimage_image_alter_hotel_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="banner_image",
        ),
    ]
