# Generated by Django 4.2.5 on 2023-10-03 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_hotel_amenities_delete_amenities"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HotelImage",
        ),
    ]
